# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'project_march.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import resource_rc

class Ui_Project(object):
    def setupUi(self, Project):
        if not Project.objectName():
            Project.setObjectName(u"Project")
        Project.resize(1430, 859)
        self.centralwidget = QWidget(Project)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(-1, -1, 1431, 861))
        self.Main_page = QWidget()
        self.Main_page.setObjectName(u"Main_page")
        self.background_image_page1 = QLabel(self.Main_page)
        self.background_image_page1.setObjectName(u"background_image_page1")
        self.background_image_page1.setGeometry(QRect(-10, -10, 1451, 871))
        self.background_image_page1.setPixmap(QPixmap(u":/Images/Static/background.webp"))
        self.background_image_page1.setScaledContents(True)
        self.label = QLabel(self.Main_page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 40, 211, 61))
        self.label.setPixmap(QPixmap(u":/Images/Static/LogoMakr-0NnMg3.png"))
        self.login_btn_to_direct = QPushButton(self.Main_page)
        self.login_btn_to_direct.setObjectName(u"login_btn_to_direct")
        self.login_btn_to_direct.setGeometry(QRect(1070, 40, 131, 51))
        self.login_btn_to_direct.setStyleSheet(u"font: 15pt \".AppleSystemUIFont\";\n"
"background-color: #FFF;\n"
"color: #1589FF;")
        self.login_btn_to_direct.setFlat(True)
        self.signin_btn_to_direct = QPushButton(self.Main_page)
        self.signin_btn_to_direct.setObjectName(u"signin_btn_to_direct")
        self.signin_btn_to_direct.setGeometry(QRect(1240, 40, 141, 51))
        self.signin_btn_to_direct.setStyleSheet(u"font: 15pt \".AppleSystemUIFont\";\n"
"color: #1589FF;\n"
"background-color: #FFF;")
        self.signin_btn_to_direct.setAutoDefault(False)
        self.signin_btn_to_direct.setFlat(True)
        self.label_2 = QLabel(self.Main_page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 230, 541, 91))
        self.label_2.setStyleSheet(u"font: 20pt \".AppleSystemUIFont\";\n"
"color: #A0CFEC;")
        self.label_3 = QLabel(self.Main_page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 280, 661, 141))
        self.label_3.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"color: #1589FF;")
        self.start_now_btn = QPushButton(self.Main_page)
        self.start_now_btn.setObjectName(u"start_now_btn")
        self.start_now_btn.setGeometry(QRect(70, 460, 291, 61))
        self.start_now_btn.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #1589FF;")
        self.start_now_btn.setFlat(False)
        self.stackedWidget.addWidget(self.Main_page)
        self.login_page = QWidget()
        self.login_page.setObjectName(u"login_page")
        self.background_image_page1_2 = QLabel(self.login_page)
        self.background_image_page1_2.setObjectName(u"background_image_page1_2")
        self.background_image_page1_2.setGeometry(QRect(0, 0, 1441, 861))
        self.background_image_page1_2.setStyleSheet(u"")
        self.background_image_page1_2.setPixmap(QPixmap(u":/Images/Static/background.webp"))
        self.background_image_page1_2.setScaledContents(False)
        self.label_5 = QLabel(self.login_page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 40, 211, 61))
        self.label_5.setPixmap(QPixmap(u":/Images/Static/LogoMakr-0NnMg3.png"))
        self.frame = QFrame(self.login_page)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(420, 180, 531, 581))
        self.frame.setStyleSheet(u"QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"}")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 30, 451, 61))
        self.label_4.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"")
        self.username_login = QLineEdit(self.frame)
        self.username_login.setObjectName(u"username_login")
        self.username_login.setGeometry(QRect(50, 140, 401, 41))
        self.username_login.setStyleSheet(u"background-color: #F8F6F0;")
        self.password_line = QLineEdit(self.frame)
        self.password_line.setObjectName(u"password_line")
        self.password_line.setGeometry(QRect(50, 320, 401, 41))
        self.password_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.password_line.setEchoMode(QLineEdit.Password)
        self.login_btn = QPushButton(self.frame)
        self.login_btn.setObjectName(u"login_btn")
        self.login_btn.setGeometry(QRect(160, 430, 181, 51))
        self.login_btn.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #1589FF;")
        self.login_btn.setFlat(False)
        self.email_line = QLineEdit(self.frame)
        self.email_line.setObjectName(u"email_line")
        self.email_line.setGeometry(QRect(50, 230, 401, 41))
        self.email_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.label_8 = QLabel(self.login_page)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(1010, 40, 221, 61))
        self.label_8.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"")
        self.signup_btn_to_signuppage = QPushButton(self.login_page)
        self.signup_btn_to_signuppage.setObjectName(u"signup_btn_to_signuppage")
        self.signup_btn_to_signuppage.setGeometry(QRect(1240, 50, 151, 41))
        self.signup_btn_to_signuppage.setStyleSheet(u"QPushButton{\n"
"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #1589FF;\n"
"}")
        self.signup_btn_to_signuppage.setFlat(False)
        self.stackedWidget.addWidget(self.login_page)
        self.signup_page = QWidget()
        self.signup_page.setObjectName(u"signup_page")
        self.login_btn_to_loginpage = QPushButton(self.signup_page)
        self.login_btn_to_loginpage.setObjectName(u"login_btn_to_loginpage")
        self.login_btn_to_loginpage.setGeometry(QRect(1260, 40, 141, 41))
        self.login_btn_to_loginpage.setStyleSheet(u"font: 12pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #1589FF;")
        self.login_btn_to_loginpage.setFlat(False)
        self.label_9 = QLabel(self.signup_page)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(1050, 30, 201, 61))
        self.label_9.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"")
        self.background_image_page1_3 = QLabel(self.signup_page)
        self.background_image_page1_3.setObjectName(u"background_image_page1_3")
        self.background_image_page1_3.setGeometry(QRect(0, 0, 1431, 861))
        self.background_image_page1_3.setPixmap(QPixmap(u":/Images/Static/background.webp"))
        self.background_image_page1_3.setScaledContents(True)
        self.frame_2 = QFrame(self.signup_page)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(470, 110, 511, 681))
        self.frame_2.setStyleSheet(u"QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px\n"
"}")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.frame_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 30, 461, 61))
        self.label_10.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"")
        self.nom_line = QLineEdit(self.frame_2)
        self.nom_line.setObjectName(u"nom_line")
        self.nom_line.setGeometry(QRect(50, 200, 401, 41))
        self.nom_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.prenom_line = QLineEdit(self.frame_2)
        self.prenom_line.setObjectName(u"prenom_line")
        self.prenom_line.setGeometry(QRect(50, 280, 401, 41))
        self.prenom_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.sign_email_line = QLineEdit(self.frame_2)
        self.sign_email_line.setObjectName(u"sign_email_line")
        self.sign_email_line.setGeometry(QRect(50, 360, 401, 41))
        self.sign_email_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.sign_password_line = QLineEdit(self.frame_2)
        self.sign_password_line.setObjectName(u"sign_password_line")
        self.sign_password_line.setGeometry(QRect(50, 440, 401, 41))
        self.sign_password_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.sign_password_line.setEchoMode(QLineEdit.Password)
        self.confirm_password = QLineEdit(self.frame_2)
        self.confirm_password.setObjectName(u"confirm_password")
        self.confirm_password.setGeometry(QRect(50, 520, 401, 41))
        self.confirm_password.setStyleSheet(u"background-color: #F8F6F0;")
        self.confirm_password.setEchoMode(QLineEdit.Password)
        self.signup_btn = QPushButton(self.frame_2)
        self.signup_btn.setObjectName(u"signup_btn")
        self.signup_btn.setGeometry(QRect(160, 590, 181, 51))
        self.signup_btn.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #1589FF;")
        self.signup_btn.setFlat(False)
        self.username_sign = QLineEdit(self.frame_2)
        self.username_sign.setObjectName(u"username_sign")
        self.username_sign.setGeometry(QRect(50, 120, 401, 41))
        self.username_sign.setStyleSheet(u"background-color: #F8F6F0;")
        self.label_17 = QLabel(self.signup_page)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 40, 211, 61))
        self.label_17.setPixmap(QPixmap(u":/Images/Static/LogoMakr-0NnMg3.png"))
        self.stackedWidget.addWidget(self.signup_page)
        self.background_image_page1_3.raise_()
        self.login_btn_to_loginpage.raise_()
        self.label_9.raise_()
        self.frame_2.raise_()
        self.label_17.raise_()
        self.home_page = QWidget()
        self.home_page.setObjectName(u"home_page")
        self.frame_5 = QFrame(self.home_page)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, 90, 391, 771))
        self.frame_5.setStyleSheet(u"background-color: #123456;")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.label_11 = QLabel(self.frame_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(-10, 40, 401, 41))
        self.label_11.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.signup_btn_2 = QPushButton(self.frame_5)
        self.signup_btn_2.setObjectName(u"signup_btn_2")
        self.signup_btn_2.setGeometry(QRect(-50, 110, 341, 71))
        self.signup_btn_2.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color: #123456;")
        self.signup_btn_2.setFlat(True)
        self.signup_btn_3 = QPushButton(self.frame_5)
        self.signup_btn_3.setObjectName(u"signup_btn_3")
        self.signup_btn_3.setGeometry(QRect(-50, 190, 321, 71))
        self.signup_btn_3.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color: #123456;")
        self.signup_btn_3.setFlat(True)
        self.signup_btn_4 = QPushButton(self.frame_5)
        self.signup_btn_4.setObjectName(u"signup_btn_4")
        self.signup_btn_4.setGeometry(QRect(-50, 270, 361, 71))
        self.signup_btn_4.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color: #123456;")
        self.signup_btn_4.setFlat(True)
        self.signup_btn_5 = QPushButton(self.frame_5)
        self.signup_btn_5.setObjectName(u"signup_btn_5")
        self.signup_btn_5.setGeometry(QRect(-110, 340, 451, 71))
        self.signup_btn_5.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color: #123456;")
        self.signup_btn_5.setFlat(True)
        self.signup_btn_6 = QPushButton(self.frame_5)
        self.signup_btn_6.setObjectName(u"signup_btn_6")
        self.signup_btn_6.setGeometry(QRect(-170, 420, 571, 61))
        self.signup_btn_6.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color: #123456;")
        self.signup_btn_6.setFlat(True)
        self.signup_btn_7 = QPushButton(self.frame_5)
        self.signup_btn_7.setObjectName(u"signup_btn_7")
        self.signup_btn_7.setGeometry(QRect(-70, 480, 351, 71))
        self.signup_btn_7.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color: #123456;")
        self.signup_btn_7.setFlat(True)
        self.line_3 = QFrame(self.frame_5)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(0, 170, 391, 31))
        self.line_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.frame_5)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(0, 250, 391, 31))
        self.line_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(self.frame_5)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(0, 330, 391, 31))
        self.line_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_6 = QFrame(self.frame_5)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(0, 400, 391, 31))
        self.line_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_7 = QFrame(self.frame_5)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(0, 470, 391, 31))
        self.line_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_8 = QFrame(self.frame_5)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(0, 540, 391, 31))
        self.line_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.line_9 = QFrame(self.frame_5)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(0, 90, 391, 31))
        self.line_9.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.home_page)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(380, 90, 20, 771))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.background_image_page1_4 = QLabel(self.home_page)
        self.background_image_page1_4.setObjectName(u"background_image_page1_4")
        self.background_image_page1_4.setGeometry(QRect(0, 0, 1431, 861))
        self.background_image_page1_4.setPixmap(QPixmap(u":/Images/Static/background.webp"))
        self.background_image_page1_4.setScaledContents(True)
        self.label_6 = QLabel(self.home_page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(390, 90, 1041, 771))
        self.frame_3 = QFrame(self.home_page)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 0, 1431, 91))
        self.frame_3.setStyleSheet(u"background-color: #123456;")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.nom_line_2 = QLineEdit(self.frame_3)
        self.nom_line_2.setObjectName(u"nom_line_2")
        self.nom_line_2.setGeometry(QRect(990, 30, 341, 41))
        self.nom_line_2.setStyleSheet(u"background-color: #F8F6F0;")
        self.label_14 = QLabel(self.frame_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(30, 20, 211, 61))
        self.label_14.setPixmap(QPixmap(u":/Images/Static/LogoMakr-0NnMg3.png"))
        self.profile = QPushButton(self.frame_3)
        self.profile.setObjectName(u"profile")
        self.profile.setGeometry(QRect(1340, 20, 71, 61))
        self.profile.setCursor(QCursor(Qt.PointingHandCursor))
        self.profile.setStyleSheet(u"")
        icon = QIcon()
        icon.addFile(u":/Images/Static/account_32px.png", QSize(), QIcon.Normal, QIcon.Off)
        self.profile.setIcon(icon)
        self.profile.setIconSize(QSize(100, 100))
        self.profile.setFlat(True)
        self.pushButton_2 = QPushButton(self.frame_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(920, 20, 71, 61))
        self.pushButton_2.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u":/Images/Static/search_24px.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QSize(50, 50))
        self.pushButton_2.setFlat(True)
        self.profile_result = QFrame(self.home_page)
        self.profile_result.setObjectName(u"profile_result")
        self.profile_result.setGeometry(QRect(980, 90, 451, 351))
        self.profile_result.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.profile_result.setFrameShape(QFrame.StyledPanel)
        self.profile_result.setFrameShadow(QFrame.Raised)
        self.label_15 = QLabel(self.profile_result)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(60, 150, 231, 41))
        self.label_12 = QLabel(self.profile_result)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(60, 200, 341, 41))
        self.disconnected = QPushButton(self.profile_result)
        self.disconnected.setObjectName(u"disconnected")
        self.disconnected.setGeometry(QRect(290, 290, 141, 41))
        self.disconnected.setStyleSheet(u"font: 12pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #FD1C03;")
        self.disconnected.setFlat(False)
        self.label_16 = QLabel(self.profile_result)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(170, 20, 121, 121))
        self.label_16.setPixmap(QPixmap(u":/Images/Static/images (2)logo.png"))
        self.label_16.setScaledContents(True)
        self.line_10 = QFrame(self.profile_result)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(50, 180, 341, 16))
        self.line_10.setFrameShape(QFrame.HLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.line_11 = QFrame(self.profile_result)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(50, 230, 341, 16))
        self.line_11.setFrameShape(QFrame.HLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.line = QFrame(self.home_page)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 70, 1431, 41))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.stackedWidget.addWidget(self.home_page)
        self.background_image_page1_4.raise_()
        self.frame_5.raise_()
        self.line_2.raise_()
        self.label_6.raise_()
        self.frame_3.raise_()
        self.profile_result.raise_()
        self.line.raise_()
        Project.setCentralWidget(self.centralwidget)

        self.retranslateUi(Project)

        self.stackedWidget.setCurrentIndex(0)
        self.login_btn_to_direct.setDefault(False)
        self.signin_btn_to_direct.setDefault(False)
        self.start_now_btn.setDefault(True)
        self.login_btn.setDefault(True)
        self.signup_btn_to_signuppage.setDefault(True)
        self.login_btn_to_loginpage.setDefault(True)
        self.signup_btn.setDefault(True)
        self.signup_btn_2.setDefault(False)
        self.signup_btn_3.setDefault(False)
        self.signup_btn_4.setDefault(False)
        self.signup_btn_5.setDefault(False)
        self.signup_btn_6.setDefault(False)
        self.signup_btn_7.setDefault(False)
        self.profile.setDefault(False)
        self.disconnected.setDefault(True)


        QMetaObject.connectSlotsByName(Project)
    # setupUi

    def retranslateUi(self, Project):
        Project.setWindowTitle(QCoreApplication.translate("Project", u"MainWindow", None))
        self.background_image_page1.setText("")
        self.label.setText("")
        self.login_btn_to_direct.setText(QCoreApplication.translate("Project", u"Connexion", None))
        self.signin_btn_to_direct.setText(QCoreApplication.translate("Project", u"S'inscrire", None))
        self.label_2.setText(QCoreApplication.translate("Project", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Bienvenue sur Code Breaker</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("Project", u"<html><head/><body><p>Rejoignez les millions d'apprenants \u00e0 coder </p><p>avec Code Breaker gratuitement</p></body></html>", None))
        self.start_now_btn.setText(QCoreApplication.translate("Project", u"Commencez maintenant", None))
        self.background_image_page1_2.setText("")
        self.label_5.setText("")
        self.label_4.setText(QCoreApplication.translate("Project", u"<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline;\">Connectez-vous \u00e0 Code Breaker</span></p></body></html>", None))
        self.username_login.setPlaceholderText(QCoreApplication.translate("Project", u"Nom d'utilisateur", None))
        self.password_line.setPlaceholderText(QCoreApplication.translate("Project", u"Mot de passe", None))
        self.login_btn.setText(QCoreApplication.translate("Project", u"Connexion", None))
        self.email_line.setPlaceholderText(QCoreApplication.translate("Project", u"Email", None))
        self.label_8.setText(QCoreApplication.translate("Project", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Vous n'avez pas de compte ?</span></p></body></html>", None))
        self.signup_btn_to_signuppage.setText(QCoreApplication.translate("Project", u"S'inscrire", None))
        self.login_btn_to_loginpage.setText(QCoreApplication.translate("Project", u"Connexion", None))
        self.label_9.setText(QCoreApplication.translate("Project", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Vous avez d\u00e9j\u00e0 un compte?</span></p></body></html>", None))
        self.background_image_page1_3.setText("")
        self.label_10.setText(QCoreApplication.translate("Project", u"<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline;\">Inscrivez-vous \u00e0 Code Breaker</span></p></body></html>", None))
        self.nom_line.setPlaceholderText(QCoreApplication.translate("Project", u"Nom", None))
        self.prenom_line.setPlaceholderText(QCoreApplication.translate("Project", u"Prenom", None))
        self.sign_email_line.setPlaceholderText(QCoreApplication.translate("Project", u"Email", None))
        self.sign_password_line.setPlaceholderText(QCoreApplication.translate("Project", u"Mot de passe", None))
        self.confirm_password.setPlaceholderText(QCoreApplication.translate("Project", u"Confirmez le mot de passe", None))
        self.signup_btn.setText(QCoreApplication.translate("Project", u"S'inscrire", None))
        self.username_sign.setPlaceholderText(QCoreApplication.translate("Project", u"Nom d'utilisateur", None))
        self.label_17.setText("")
        self.label_11.setText(QCoreApplication.translate("Project", u"<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline;\">Language de progammation</span></p><p align=\"center\"><span style=\" text-decoration: underline;\"><br/></span></p></body></html>", None))
        self.signup_btn_2.setText(QCoreApplication.translate("Project", u"\u26ac HTML", None))
        self.signup_btn_3.setText(QCoreApplication.translate("Project", u"\u26ac CSS", None))
        self.signup_btn_4.setText(QCoreApplication.translate("Project", u"\u26ac JavaScript", None))
        self.signup_btn_5.setText(QCoreApplication.translate("Project", u"\u26ac Python", None))
        self.signup_btn_6.setText(QCoreApplication.translate("Project", u"\u26ac Flutter", None))
        self.signup_btn_7.setText(QCoreApplication.translate("Project", u"\u26ac PHP", None))
        self.background_image_page1_4.setText("")
        self.label_6.setText(QCoreApplication.translate("Project", u"TextLabel", None))
        self.nom_line_2.setPlaceholderText(QCoreApplication.translate("Project", u"Rechercher un language de progammation", None))
        self.label_14.setText("")
        self.profile.setText("")
        self.pushButton_2.setText("")
        self.label_15.setText("")
        self.label_12.setText("")
        self.disconnected.setText(QCoreApplication.translate("Project", u"Se D\u00e9conneter", None))
        self.label_16.setText("")
    # retranslateUi

