# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'project_march.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import resource_rc

class Ui_Project(object):
    def setupUi(self, Project):
        if not Project.objectName():
            Project.setObjectName(u"Project")
        Project.resize(1430, 860)
        self.centralwidget = QWidget(Project)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(-1, -1, 1431, 861))
        self.Main_page = QWidget()
        self.Main_page.setObjectName(u"Main_page")
        self.background_image_page1 = QLabel(self.Main_page)
        self.background_image_page1.setObjectName(u"background_image_page1")
        self.background_image_page1.setGeometry(QRect(-10, -10, 1451, 871))
        self.background_image_page1.setPixmap(QPixmap(u":/Images/Static/background.webp"))
        self.background_image_page1.setScaledContents(True)
        self.label = QLabel(self.Main_page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 40, 211, 51))
        self.label.setPixmap(QPixmap(u":/Images/Static/LogoMakr-80ZEB9.png"))
        self.login_btn_to_direct = QPushButton(self.Main_page)
        self.login_btn_to_direct.setObjectName(u"login_btn_to_direct")
        self.login_btn_to_direct.setGeometry(QRect(1070, 40, 131, 51))
        self.login_btn_to_direct.setStyleSheet(u"font: 15pt \".AppleSystemUIFont\";\n"
"background-color: #FFF;\n"
"color: #1589FF;")
        self.login_btn_to_direct.setFlat(True)
        self.signin_btn_to_direct = QPushButton(self.Main_page)
        self.signin_btn_to_direct.setObjectName(u"signin_btn_to_direct")
        self.signin_btn_to_direct.setGeometry(QRect(1240, 40, 141, 51))
        self.signin_btn_to_direct.setStyleSheet(u"font: 15pt \".AppleSystemUIFont\";\n"
"color: #1589FF;\n"
"background-color: #FFF;")
        self.signin_btn_to_direct.setAutoDefault(False)
        self.signin_btn_to_direct.setFlat(True)
        self.label_2 = QLabel(self.Main_page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 230, 541, 91))
        self.label_2.setStyleSheet(u"font: 20pt \".AppleSystemUIFont\";\n"
"color: #A0CFEC;")
        self.label_3 = QLabel(self.Main_page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 270, 661, 141))
        self.label_3.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"color: #1589FF;")
        self.start_now_btn = QPushButton(self.Main_page)
        self.start_now_btn.setObjectName(u"start_now_btn")
        self.start_now_btn.setGeometry(QRect(70, 450, 291, 61))
        self.start_now_btn.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #1589FF;")
        self.start_now_btn.setFlat(False)
        self.stackedWidget.addWidget(self.Main_page)
        self.login_page = QWidget()
        self.login_page.setObjectName(u"login_page")
        self.background_image_page1_2 = QLabel(self.login_page)
        self.background_image_page1_2.setObjectName(u"background_image_page1_2")
        self.background_image_page1_2.setGeometry(QRect(0, 0, 1441, 861))
        self.background_image_page1_2.setStyleSheet(u"")
        self.background_image_page1_2.setPixmap(QPixmap(u":/Images/Static/background.webp"))
        self.background_image_page1_2.setScaledContents(True)
        self.label_5 = QLabel(self.login_page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 40, 211, 51))
        self.label_5.setPixmap(QPixmap(u":/Images/Static/LogoMakr-80ZEB9.png"))
        self.frame = QFrame(self.login_page)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(420, 180, 531, 461))
        self.frame.setStyleSheet(u"QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"}")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 30, 451, 61))
        self.label_4.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"")
        self.email_line = QLineEdit(self.frame)
        self.email_line.setObjectName(u"email_line")
        self.email_line.setGeometry(QRect(50, 130, 401, 41))
        self.email_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.password_line = QLineEdit(self.frame)
        self.password_line.setObjectName(u"password_line")
        self.password_line.setGeometry(QRect(50, 230, 401, 41))
        self.password_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.password_line.setEchoMode(QLineEdit.Password)
        self.login_btn = QPushButton(self.frame)
        self.login_btn.setObjectName(u"login_btn")
        self.login_btn.setGeometry(QRect(160, 340, 181, 51))
        self.login_btn.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #1589FF;")
        self.login_btn.setFlat(False)
        self.label_8 = QLabel(self.login_page)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(1010, 40, 221, 61))
        self.label_8.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"")
        self.signup_btn_to_signuppage = QPushButton(self.login_page)
        self.signup_btn_to_signuppage.setObjectName(u"signup_btn_to_signuppage")
        self.signup_btn_to_signuppage.setGeometry(QRect(1240, 50, 151, 41))
        self.signup_btn_to_signuppage.setStyleSheet(u"QPushButton{\n"
"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #1589FF;\n"
"}")
        self.signup_btn_to_signuppage.setFlat(False)
        self.stackedWidget.addWidget(self.login_page)
        self.signup_page = QWidget()
        self.signup_page.setObjectName(u"signup_page")
        self.login_btn_to_loginpage = QPushButton(self.signup_page)
        self.login_btn_to_loginpage.setObjectName(u"login_btn_to_loginpage")
        self.login_btn_to_loginpage.setGeometry(QRect(1260, 40, 141, 41))
        self.login_btn_to_loginpage.setStyleSheet(u"font: 12pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #1589FF;")
        self.login_btn_to_loginpage.setFlat(False)
        self.label_9 = QLabel(self.signup_page)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(1050, 30, 201, 61))
        self.label_9.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"")
        self.background_image_page1_3 = QLabel(self.signup_page)
        self.background_image_page1_3.setObjectName(u"background_image_page1_3")
        self.background_image_page1_3.setGeometry(QRect(0, 0, 1431, 861))
        self.background_image_page1_3.setPixmap(QPixmap(u":/Images/Static/background.webp"))
        self.background_image_page1_3.setScaledContents(True)
        self.frame_2 = QFrame(self.signup_page)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(470, 110, 511, 681))
        self.frame_2.setStyleSheet(u"QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px\n"
"}")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.frame_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 30, 461, 61))
        self.label_10.setStyleSheet(u"font: 16pt \".AppleSystemUIFont\";\n"
"")
        self.nom_line = QLineEdit(self.frame_2)
        self.nom_line.setObjectName(u"nom_line")
        self.nom_line.setGeometry(QRect(50, 130, 401, 41))
        self.nom_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.prenom_line = QLineEdit(self.frame_2)
        self.prenom_line.setObjectName(u"prenom_line")
        self.prenom_line.setGeometry(QRect(50, 220, 401, 41))
        self.prenom_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.sign_email_line = QLineEdit(self.frame_2)
        self.sign_email_line.setObjectName(u"sign_email_line")
        self.sign_email_line.setGeometry(QRect(50, 310, 401, 41))
        self.sign_email_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.sign_password_line = QLineEdit(self.frame_2)
        self.sign_password_line.setObjectName(u"sign_password_line")
        self.sign_password_line.setGeometry(QRect(50, 400, 401, 41))
        self.sign_password_line.setStyleSheet(u"background-color: #F8F6F0;")
        self.sign_password_line.setEchoMode(QLineEdit.Password)
        self.confirm_password = QLineEdit(self.frame_2)
        self.confirm_password.setObjectName(u"confirm_password")
        self.confirm_password.setGeometry(QRect(50, 490, 401, 41))
        self.confirm_password.setStyleSheet(u"background-color: #F8F6F0;")
        self.confirm_password.setEchoMode(QLineEdit.Password)
        self.signup_btn = QPushButton(self.frame_2)
        self.signup_btn.setObjectName(u"signup_btn")
        self.signup_btn.setGeometry(QRect(160, 580, 181, 51))
        self.signup_btn.setStyleSheet(u"font: 14pt \".AppleSystemUIFont\";\n"
"color:#FFF;\n"
"background-color:  #1589FF;")
        self.signup_btn.setFlat(False)
        self.label_13 = QLabel(self.signup_page)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(40, 40, 211, 51))
        self.label_13.setPixmap(QPixmap(u":/Images/Static/LogoMakr-80ZEB9.png"))
        self.stackedWidget.addWidget(self.signup_page)
        self.background_image_page1_3.raise_()
        self.login_btn_to_loginpage.raise_()
        self.label_9.raise_()
        self.frame_2.raise_()
        self.label_13.raise_()
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.background_image_page1_4 = QLabel(self.page)
        self.background_image_page1_4.setObjectName(u"background_image_page1_4")
        self.background_image_page1_4.setGeometry(QRect(0, 0, 1431, 861))
        self.background_image_page1_4.setPixmap(QPixmap(u":/Images/Static/background.webp"))
        self.background_image_page1_4.setScaledContents(True)
        self.label_14 = QLabel(self.page)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(40, 40, 211, 51))
        self.label_14.setPixmap(QPixmap(u":/Images/Static/LogoMakr-80ZEB9.png"))
        self.nom_line_2 = QLineEdit(self.page)
        self.nom_line_2.setObjectName(u"nom_line_2")
        self.nom_line_2.setGeometry(QRect(960, 40, 341, 41))
        self.nom_line_2.setStyleSheet(u"background-color: #F8F6F0;")
        self.pushButton = QPushButton(self.page)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(900, 40, 51, 41))
        icon = QIcon()
        icon.addFile(u":/Images/Static/icons8-search-32.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QSize(100, 100))
        self.pushButton.setFlat(True)
        self.pushButton_2 = QPushButton(self.page)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(1320, 30, 51, 51))
        self.pushButton_2.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u":/Images/Static/images-removebg-preview.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QSize(50, 50))
        self.pushButton_2.setFlat(True)
        self.stackedWidget.addWidget(self.page)
        Project.setCentralWidget(self.centralwidget)

        self.retranslateUi(Project)

        self.stackedWidget.setCurrentIndex(0)
        self.login_btn_to_direct.setDefault(False)
        self.signin_btn_to_direct.setDefault(False)
        self.start_now_btn.setDefault(True)
        self.login_btn.setDefault(True)
        self.signup_btn_to_signuppage.setDefault(True)
        self.login_btn_to_loginpage.setDefault(True)
        self.signup_btn.setDefault(True)
        self.pushButton.setDefault(True)
        self.pushButton_2.setDefault(True)


        QMetaObject.connectSlotsByName(Project)
    # setupUi

    def retranslateUi(self, Project):
        Project.setWindowTitle(QCoreApplication.translate("Project", u"MainWindow", None))
        self.background_image_page1.setText("")
        self.label.setText("")
        self.login_btn_to_direct.setText(QCoreApplication.translate("Project", u"Connexion", None))
        self.signin_btn_to_direct.setText(QCoreApplication.translate("Project", u"S'inscrire", None))
        self.label_2.setText(QCoreApplication.translate("Project", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Bienvenue sur Code Breaker</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("Project", u"<html><head/><body><p>Rejoignez les millions d'apprenants \u00e0 coder </p><p>avec Code Breaker gratuitement</p></body></html>", None))
        self.start_now_btn.setText(QCoreApplication.translate("Project", u"Commencez maintenant", None))
        self.background_image_page1_2.setText("")
        self.label_5.setText("")
        self.label_4.setText(QCoreApplication.translate("Project", u"<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline;\">Connectez-vous \u00e0 Code Breaker</span></p></body></html>", None))
        self.email_line.setPlaceholderText(QCoreApplication.translate("Project", u"Email", None))
        self.password_line.setPlaceholderText(QCoreApplication.translate("Project", u"Mot de passe", None))
        self.login_btn.setText(QCoreApplication.translate("Project", u"Connexion", None))
        self.label_8.setText(QCoreApplication.translate("Project", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Vous n'avez pas de compte ?</span></p></body></html>", None))
        self.signup_btn_to_signuppage.setText(QCoreApplication.translate("Project", u"S'inscrire", None))
        self.login_btn_to_loginpage.setText(QCoreApplication.translate("Project", u"Connexion", None))
        self.label_9.setText(QCoreApplication.translate("Project", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Vous avez d\u00e9j\u00e0 un compte?</span></p></body></html>", None))
        self.background_image_page1_3.setText("")
        self.label_10.setText(QCoreApplication.translate("Project", u"<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline;\">Inscrivez-vous \u00e0 Code Breaker</span></p></body></html>", None))
        self.nom_line.setPlaceholderText(QCoreApplication.translate("Project", u"Nom", None))
        self.prenom_line.setPlaceholderText(QCoreApplication.translate("Project", u"Prenom", None))
        self.sign_email_line.setPlaceholderText(QCoreApplication.translate("Project", u"Email", None))
        self.sign_password_line.setPlaceholderText(QCoreApplication.translate("Project", u"Mot de passe", None))
        self.confirm_password.setPlaceholderText(QCoreApplication.translate("Project", u"Confirmez le mot de passe", None))
        self.signup_btn.setText(QCoreApplication.translate("Project", u"S'inscrire", None))
        self.label_13.setText("")
        self.background_image_page1_4.setText("")
        self.label_14.setText("")
        self.nom_line_2.setPlaceholderText(QCoreApplication.translate("Project", u"Rechercher un language de progammation", None))
        self.pushButton.setText("")
        self.pushButton_2.setText("")
    # retranslateUi

